apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: dev-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox-d
  template:
    metadata:
      labels:
        app: busybox-d
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["sleep", "3000"]
